### PR TITLE
Add recommendation monitoring to online evaluation monitor

### PR DESCRIPTION
**Pull request by gabrieltseng**

### CODE REVIEW

**Review by StevenYuan666 — COMMENTED** [review]
I'm wondering if we still need to check `if parsed[2].find("recommendation request") != -1` since it might not be a recommendation request?

**Comment by gabrieltseng** [comment]
> I'm wondering if we still need to check if parsed[2].find("recommendation request") != -1 since it might not be a recommendation request?

@StevenYuan666 yes we do still! its still within the `if` statement on line `121`

**Comment by StevenYuan666** [comment]
> 

Oh my bad. I had look on the file changes and did not notice the top line

**Comment by gabrieltseng** [comment]
@StevenYuan666 , sorry I requested a review early; I think I confused this PR with #25 .

It's actually ready for review now, since we can send emails thanks to #24 - only change is to add the [send_email](https://github.com/COMP585Fall2022/Team-5/pull/27/commits/acd9db7729bb4fdf1d7ea075364dfbe0ea86d3a2) function to the monitoring.

**Review by StevenYuan666 — APPROVED** [review]
Great Job!!

**Pull request merged**
