### PR TITLE
Track Metrics By Last Digit of User ID

### PR DESCRIPTION
**Pull request by StevenYuan666**
- [x] Modify the monitor.py so that we can track the five online evluation metrics based on the last digit of users' IDs

### CODE REVIEW

**Comment by gabrieltseng** [comment]
Nice job @StevenYuan666 this looks good! have you deployed it / do you have a screenshot of the example output?

**Comment by StevenYuan666** [comment]
> Nice job @StevenYuan666 this looks good! have you deployed it / do you have a screenshot of the example output?

I've not deployed this part yet. This part will be used to decide whether or not we will abort the new model. However, I have an example output when I test it on local:

`1668968190
Watch rate: [0.0, 0.034482758620689655, 0.014492753623188406, 0.03278688524590164, 0.0, 0.02040816326530612, 0.013157894736842105, 0.014925373134328358, 0.017543859649122806, 0.013157894736842105]
Average Watch rate: 0.01609555830122212
Good rating proportion: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Average Good rating proportion: 0
Watch time proportion: [0, 0.014084507042253521, 0.014084507042253521, 0.008620689655172414, 0, 0.014084507042253521, 0.011428571428571429, 0.008403361344537815, 0.005917159763313609, 0.0056179775280898875]
Average watch time proportion: 0.008224128084644572
Watch rank: [0, 1.0, 1.0, 3.5, 0, 1.0, 7.0, 2.0, 2.0, 4.0]
Avg watch rank: 2.15
recommended proportion in total watched: [0, 1.0, 1.0, 0.6666666666666666, 0, 1.0, 0.5, 1.0, 1.0, 1.0]
Average recommended proportion in total watched: 0.7166666666666667`

**Review by gabrieltseng — APPROVED** [review]
Awesome - that makes sense. Thanks @StevenYuan666  :)

**Comment by StevenYuan666** [comment]
@Eggie-Wu Required by Eggie, I refactor the monitoring part by tracking two groups of users (one for canary model, another one for live model). Meanwhile, I delete the code for checking the availability (i.e., checking the status is 200). Eggie will split that part into another file.

**Comment by StevenYuan666** [comment]
> @Eggie-Wu Required by Eggie, I refactor the monitoring part by tracking two groups of users (one for canary model, another one for live model). Meanwhile, I delete the code for checking the availability (i.e., checking the status is 200). Eggie will split that part into another file.

After this change, the log file will be like:
`1669272671
Watch rate: [0.0, 0.003]
Average Watch rate: 0.0015
Good rating proportion: [0, 0]
Average Good rating proportion: 0
Watch time proportion: [0, 0.01971326164874552]
Average watch time proportion: 0.00985663082437276
Watch rank: [0, 4.0]
Avg watch rank: 2.0
recommended proportion in total watched: [0, 0.75]
Average recommended proportion in total watched: 0.375`

The index 0 is the metric for canary model, and index 1 is the metric for live model

**Review by Eggie-Wu — APPROVED** [review]
Will modify when debug/deploy

**Pull request merged**
